services:
  postgres:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_USER: ylesfer
      POSTGRES_PASSWORD: ad201449
      POSTGRES_DB: socially_DB
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: {}
